Repository blocto/blocto-sdk, pull requests merged in 2023-09, with the labels that each got.

#262 chore: fix build failed with cache and changed PR bot token
  .github/workflows/release-branch.yml
  .github/workflows/test.yml
Labels: BugFix

#261 fix: skip calling enable() when request wallet_disconnect method
  .changeset/gold-kids-grin.md
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: BugFix

#239 fix: clear web3 react connector error
  .changeset/perfect-roses-enjoy.md
  .changeset/proud-clocks-lick.md
  .changeset/rare-mice-watch.md
  .gitignore
  adapters/web3-react-connector/src/index.ts
  examples/with-evm-web3-react-next/README.md
  examples/with-evm-web3-react-next/chains.ts
  examples/with-evm-web3-react-next/components/Accounts.tsx
  examples/with-evm-web3-react-next/components/Card.tsx
  examples/with-evm-web3-react-next/components/Chain.tsx
  examples/with-evm-web3-react-next/components/ConnectWithSelect.tsx
  examples/with-evm-web3-react-next/components/ProviderExample.tsx
  examples/with-evm-web3-react-next/components/Status.tsx
  examples/with-evm-web3-react-next/components/connectorCards/BloctoCard.tsx
  examples/with-evm-web3-react-next/components/connectorCards/CoinbaseWalletCard.tsx
  examples/with-evm-web3-react-next/components/connectorCards/GnosisSafeCard.tsx
  examples/with-evm-web3-react-next/components/connectorCards/MetaMaskCard.tsx
  examples/with-evm-web3-react-next/components/connectorCards/NetworkCard.tsx
  examples/with-evm-web3-react-next/components/connectorCards/WalletConnectCard.tsx
  examples/with-evm-web3-react-next/components/connectorCards/WalletConnectV2Card.tsx
  examples/with-evm-web3-react-next/connectors/bloctoSdk.ts
  examples/with-evm-web3-react-next/connectors/coinbaseWallet.ts
  examples/with-evm-web3-react-next/connectors/eip1193.ts
  examples/with-evm-web3-react-next/connectors/empty.ts
  examples/with-evm-web3-react-next/connectors/gnosisSafe.ts
  examples/with-evm-web3-react-next/connectors/metaMask.ts
  examples/with-evm-web3-react-next/connectors/network.ts
  examples/with-evm-web3-react-next/connectors/url.ts
  examples/with-evm-web3-react-next/connectors/walletConnect.ts
  examples/with-evm-web3-react-next/connectors/walletConnectV2.ts
  examples/with-evm-web3-react-next/next-env.d.ts
  examples/with-evm-web3-react-next/next.config.js
  examples/with-evm-web3-react-next/package.json
  examples/with-evm-web3-react-next/pages/index.tsx
  examples/with-evm-web3-react-next/tsconfig.json
  examples/with-evm-web3-react-next/utils.ts
  examples/with-evm-web3-react-next/yarn.lock
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: BugFix

#266 fix: wrongly disconnect provider
  .changeset/blue-pandas-switch.md
  .changeset/pre.json
  adapters/aptos-wallet-adapter-plugin/CHANGELOG.md
  adapters/aptos-wallet-adapter-plugin/package.json
  adapters/connectkit-connector/CHANGELOG.md
  adapters/connectkit-connector/package.json
  adapters/rainbowkit-connector/CHANGELOG.md
  adapters/rainbowkit-connector/package.json
  adapters/wagmi-connector/CHANGELOG.md
  adapters/wagmi-connector/package.json
  adapters/web3-react-connector/CHANGELOG.md
  adapters/web3-react-connector/package.json
  adapters/web3modal-connector/CHANGELOG.md
  adapters/web3modal-connector/package.json
  packages/blocto-sdk/CHANGELOG.md
  packages/blocto-sdk/package.json
  packages/blocto-sdk/src/lib/storage/storage.ts
  packages/blocto-sdk/src/providers/aptos.ts
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: BugFix

#267 fix(example): web3-react-next dependency
  examples/with-evm-web3-react-next/package.json
  examples/with-evm-web3-react-next/yarn.lock
Labels: BugFix

#265 Feat/adjust connectkit connector
  .changeset/fluffy-apples-try.md
  adapters/connectkit-connector/package.json
  adapters/connectkit-connector/src/bloctoConnector.ts
  adapters/connectkit-connector/src/constants/index.tsx
  adapters/connectkit-connector/src/index.ts
  adapters/connectkit-connector/src/util/normalizeChainId.ts
  yarn.lock
Labels: feature

#270 docs(wagmi): add migration guide
  adapters/wagmi-connector/README.md
Labels: documentation

#271 fix(ci): use gh cli create pull request instead
  .github/workflows/release-branch.yml
Labels: BugFix

#274 fix(ci): use protto-admin token
  .github/workflows/release-branch.yml
Labels: BugFix

#277 Feat/dappauth rollup
  .changeset/new-brooms-refuse.md
  packages/dappauth/.gitignore
  packages/dappauth/ABIs/ERC1271.js
  packages/dappauth/LICENSE
  packages/dappauth/README.md
  packages/dappauth/index.js
  packages/dappauth/package.json
  packages/dappauth/rollup.config.js
  packages/dappauth/test/contract-mock.js
  packages/dappauth/test/provider-mock.js
  packages/dappauth/test/test-utils.js
  packages/dappauth/test/test.js
  packages/dappauth/utils.js
  yarn.lock
Labels: feature

#280 fix: use type string instead to support old typescript
  .changeset/funny-elephants-thank.md
  packages/blocto-sdk/src/lib/getEvmSupport.ts
Labels: BugFix

#279 Docs/update connectkit demo
  examples/with-evm-connectkit/.gitignore
  examples/with-evm-connectkit/README.md
  examples/with-evm-connectkit/package.json
  examples/with-evm-connectkit/public/index.html
  examples/with-evm-connectkit/public/robots.txt
  examples/with-evm-connectkit/src/App.tsx
  examples/with-evm-connectkit/src/components/Connect.tsx
  examples/with-evm-connectkit/src/components/Connected.tsx
  examples/with-evm-connectkit/src/components/NetworkSwitcher.tsx
  examples/with-evm-connectkit/src/components/SendTransaction.tsx
  examples/with-evm-connectkit/src/components/SignMessage.tsx
  examples/with-evm-connectkit/src/components/SignTypedData.tsx
  examples/with-evm-connectkit/src/hooks/useDebounce.ts
  examples/with-evm-connectkit/src/index.css
  examples/with-evm-connectkit/src/index.tsx
  examples/with-evm-connectkit/src/react-app-env.d.ts
  examples/with-evm-connectkit/src/reportWebVitals.ts
  examples/with-evm-connectkit/src/setupTests.ts
  examples/with-evm-connectkit/src/utils/stringify.ts
  examples/with-evm-connectkit/src/wagmi.ts
  examples/with-evm-connectkit/yarn.lock
  yarn.lock
Labels: documentation
