Repository blocto/blocto-sdk, pull requests merged in 2023-08, with the labels that each got.

#213 fix: handle EVM switch chain if not connected
  .changeset/nasty-pumpkins-wave.md
  .changeset/pre.json
  .changeset/real-pumas-mate.md
  adapters/rainbowkit-connector/CHANGELOG.md
  adapters/rainbowkit-connector/package.json
  adapters/wagmi-connector/CHANGELOG.md
  adapters/wagmi-connector/package.json
  adapters/web3-react-connector/CHANGELOG.md
  adapters/web3-react-connector/package.json
  packages/blocto-sdk/CHANGELOG.md
  packages/blocto-sdk/package.json
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: BugFix

#214 Feat/add web3modal thirdweb next demo
  examples/with-evm-thirdweb-next/.env.example
  examples/with-evm-thirdweb-next/.eslintrc.json
  examples/with-evm-thirdweb-next/.gitignore
  examples/with-evm-thirdweb-next/LICENSE.md
  examples/with-evm-thirdweb-next/README.md
  examples/with-evm-thirdweb-next/next-env.d.ts
  examples/with-evm-thirdweb-next/next.config.js
  examples/with-evm-thirdweb-next/package.json
  examples/with-evm-thirdweb-next/pages/_app.tsx
  examples/with-evm-thirdweb-next/pages/index.tsx
  examples/with-evm-thirdweb-next/public/favicon.ico
  examples/with-evm-thirdweb-next/public/images/dashboard-preview.png
  examples/with-evm-thirdweb-next/public/images/portal-preview.png
  examples/with-evm-thirdweb-next/public/images/templates-preview.png
  examples/with-evm-thirdweb-next/public/thirdweb.svg
  examples/with-evm-thirdweb-next/styles/Home.module.css
  examples/with-evm-thirdweb-next/styles/globals.css
  examples/with-evm-thirdweb-next/tsconfig.json
  examples/with-evm-thirdweb-next/yarn.lock
  examples/with-evm-web3modal-next/.gitignore
  examples/with-evm-web3modal-next/package.json
  examples/with-evm-web3modal-next/public/favicon.ico
  examples/with-evm-web3modal-next/public/social-card.jpg
  examples/with-evm-web3modal-next/src/components/CustomButton.jsx
  examples/with-evm-web3modal-next/src/components/SendTransaction.jsx
  examples/with-evm-web3modal-next/src/components/SignMessage.jsx
  examples/with-evm-web3modal-next/src/pages/_app.jsx
  examples/with-evm-web3modal-next/src/pages/index.jsx
  examples/with-evm-web3modal-next/src/styles.css
  examples/with-evm-web3modal-next/yarn.lock
Labels: feature

#217 Feat/upgrade web3 react v8
  .changeset/gentle-bats-live.md
  .changeset/hungry-sheep-begin.md
  .changeset/pre.json
  .changeset/two-phones-hug.md
  adapters/web3-react-connector/CHANGELOG.md
  adapters/web3-react-connector/package.json
  adapters/web3-react-connector/src/declarations.d.ts
  adapters/web3-react-connector/src/index.ts
  adapters/web3-react-connector/tsconfig.json
  packages/blocto-sdk/CHANGELOG.md
  packages/blocto-sdk/package.json
  packages/blocto-sdk/src/providers/ethereum.ts
  yarn.lock
Labels: feature

#219 Feat: add switch chain UI
  .changeset/chilled-guests-applaud.md
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: feature

#227 fix: skip switch to same chain id
  .changeset/mean-carrots-type.md
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: BugFix

#226 Feat/enhance tx value check
  .changeset/two-pants-eat.md
  packages/blocto-sdk/src/__tests__/isValidTransaction.test.js
  packages/blocto-sdk/src/lib/constant.ts
  packages/blocto-sdk/src/lib/is.ts
  packages/blocto-sdk/src/lib/isEmail.ts
  packages/blocto-sdk/src/lib/isValidTransaction.ts
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: enhancement, feature

#230 Fix/wagmi connector replace rpc source
  .changeset/chatty-apricots-nail.md
  adapters/wagmi-connector/src/bloctoConnector.ts
Labels: enhancement, BugFix

#232 fix: go login flow when switching to a different blocto server
  .changeset/grumpy-queens-flash.md
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: BugFix

#231 Fix/enhance unsupport chain check
  .changeset/eighty-rabbits-begin.md
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: BugFix

#235 fix: rainbowkit demo
  examples/with-evm-rainbowkit/package.json
  examples/with-evm-rainbowkit/src/App.js
  examples/with-evm-rainbowkit/src/index.js
  examples/with-evm-rainbowkit/yarn.lock
Labels: BugFix

#228 Feat/add wagmi demo
  examples/with-evm-wagmi/.gitignore
  examples/with-evm-wagmi/README.md
  examples/with-evm-wagmi/package.json
  examples/with-evm-wagmi/public/index.html
  examples/with-evm-wagmi/src/App.tsx
  examples/with-evm-wagmi/src/components/Connect.tsx
  examples/with-evm-wagmi/src/components/Connected.tsx
  examples/with-evm-wagmi/src/components/NetworkSwitcher.tsx
  examples/with-evm-wagmi/src/components/SendTransaction.tsx
  examples/with-evm-wagmi/src/components/SignMessage.tsx
  examples/with-evm-wagmi/src/components/SignTypedData.tsx
  examples/with-evm-wagmi/src/hooks/useDebounce.ts
  examples/with-evm-wagmi/src/index.tsx
  examples/with-evm-wagmi/src/utils/stringify.ts
  examples/with-evm-wagmi/src/wagmi.ts
  examples/with-evm-wagmi/tsconfig.json
  examples/with-evm-wagmi/yarn.lock
Labels: documentation, feature

#240 fix: clear error when add not support chain
  .changeset/moody-steaks-carry.md
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: BugFix

#236 Feat: change account
  .changeset/serious-kiwis-fly.md
  .changeset/ten-bananas-share.md
  packages/blocto-sdk/src/__tests__/index.test.js
  packages/blocto-sdk/src/constants.ts
  packages/blocto-sdk/src/lib/responseSessionGuard.ts
  packages/blocto-sdk/src/lib/storage/constants.ts
  packages/blocto-sdk/src/lib/storage/index.ts
  packages/blocto-sdk/src/lib/storage/memoryStorage.ts
  packages/blocto-sdk/src/lib/storage/storage.ts
  packages/blocto-sdk/src/providers/aptos.ts
  packages/blocto-sdk/src/providers/ethereum.ts
  packages/blocto-sdk/src/providers/types/blocto.d.ts
  packages/blocto-sdk/src/providers/types/ethereum.d.ts
Labels: feature
