Repository blocto/blocto-sdk, pull requests merged in 2023-10, with the labels that each got.

#286 Fix/example evm batch transaction
  .github/dependabot.yml
  examples/with-evm-blocto-batch-transaction/package.json
  examples/with-evm-blocto-batch-transaction/yarn.lock
Labels: BugFix

#308 Feat/adjust eth accounts as not require enable
  .changeset/curvy-students-trade.md
  adapters/wagmi-connector/src/connector.ts
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: feature

#309 Feat: djust web3-react-connector's activate method
  .changeset/gorgeous-hairs-yell.md
  adapters/web3-react-connector/src/index.ts
Labels: feature

#285 feat: disable eth_sign method
  .changeset/smooth-coats-sit.md
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: feature

#324 Release: Merge to publish new version to npm
  packages/blocto-sdk/CHANGELOG.md
  packages/blocto-sdk/package.json
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: HotFix

#325 Release: Merge back new version to develop
  .changeset/smooth-coats-sit.md
  adapters/aptos-wallet-adapter-plugin/CHANGELOG.md
  adapters/aptos-wallet-adapter-plugin/package.json
  adapters/wagmi-connector/CHANGELOG.md
  adapters/wagmi-connector/package.json
  adapters/web3-react-connector/CHANGELOG.md
  adapters/web3-react-connector/package.json
  packages/blocto-sdk/CHANGELOG.md
  packages/blocto-sdk/package.json
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: HotFix

#306 fix: account change beta version
  .changeset/pre.json
  adapters/aptos-wallet-adapter-plugin/CHANGELOG.md
  adapters/connectkit-connector/CHANGELOG.md
  adapters/rainbowkit-connector/CHANGELOG.md
  adapters/wagmi-connector/CHANGELOG.md
  adapters/web3-react-connector/CHANGELOG.md
  adapters/web3modal-connector/CHANGELOG.md
  packages/blocto-sdk/CHANGELOG.md
Labels: BugFix
