Repository blocto/blocto-sdk, pull requests merged in 2023-05, with the labels that each got.

#93 docs: add npm links
  README.md
Labels: documentation, feature

#96 feat: support rainbowkit-connector
  .changeset/gold-pots-sing.md
  .changeset/witty-taxis-serve.md
  README.md
  adapters/rainbowkit-connector/README.md
  adapters/rainbowkit-connector/jest.config.js
  adapters/rainbowkit-connector/package.json
  adapters/rainbowkit-connector/src/__tests__/index.test.ts
  adapters/rainbowkit-connector/src/index.ts
  adapters/rainbowkit-connector/tsconfig.json
  packages/blocto-sdk/src/lib/frame.ts
  yarn.lock
Labels: feature

#98 fix: not getting the latest session code when other chains re-login
  .changeset/purple-lobsters-shout.md
  packages/blocto-sdk/src/index.d.ts
  packages/blocto-sdk/src/lib/responseSessionGuard.ts
  packages/blocto-sdk/src/main.ts
  packages/blocto-sdk/src/providers/aptos.ts
  packages/blocto-sdk/src/providers/blocto.ts
  packages/blocto-sdk/src/providers/ethereum.ts
  packages/blocto-sdk/src/providers/solana.ts
  packages/blocto-sdk/src/providers/types/aptos.d.ts
  packages/blocto-sdk/src/providers/types/blocto.d.ts
  packages/blocto-sdk/src/providers/types/ethereum.d.ts
  packages/blocto-sdk/src/providers/types/solana.d.ts
Labels: BugFix

#101 fix: package version
  .changeset/mean-lamps-approve.md
  .changeset/witty-taxis-serve.md
  adapters/rainbowkit-connector/package.json
Labels: feature

#104 fix: fix aptos signing formatting
  .changeset/smart-cows-camp.md
  packages/blocto-sdk/src/providers/aptos.ts
Labels: BugFix

#106 fix: ci pull-request permission
  .github/workflows/release-branch.yml
Labels: BugFix

#111 fix: node auth and fix version
  .github/workflows/publish.yml
  .github/workflows/release-branch.yml
Labels: BugFix

#115 Create LICENSE
  LICENSE
Labels: feature

#114 docs: fix rainbowkit-connector npm version
  README.md
  adapters/react-web3-connector/README.md
Labels: documentation

#116 feat: rename web3-react-connector
  README.md
  adapters/web3-react-connector/CHANGELOG.md
  adapters/web3-react-connector/README.md
  adapters/web3-react-connector/package.json
  adapters/web3-react-connector/src/declarations.d.ts
  adapters/web3-react-connector/src/index.ts
  adapters/web3-react-connector/tsconfig.json
  adapters/web3-react-connector/yarn.lock
Labels: feature

#117 feat: add goerli support
  .changeset/cool-queens-clean.md
  packages/blocto-sdk/src/constants.ts
Labels: feature

#121 Fix: typescript, eslint, and build-warnings
  .changeset/giant-kiwis-beg.md
  .eslintrc.js
  adapters/aptos-wallet-adapter-plugin/package.json
  adapters/aptos-wallet-adapter-plugin/src/index.ts
  adapters/rainbowkit-connector/package.json
  adapters/rainbowkit-connector/src/index.ts
  adapters/wagmi-connector/package.json
  adapters/wagmi-connector/src/bloctoConnector.ts
  adapters/web3-react-connector/package.json
  adapters/web3-react-connector/src/index.ts
  adapters/web3-react-connector/tsconfig.json
  package.json
  packages/blocto-sdk/.eslintrc.js
  packages/blocto-sdk/package.json
  packages/blocto-sdk/rollup.config.js
  packages/blocto-sdk/src/lib/invariant.ts
  packages/blocto-sdk/src/lib/is.ts
  packages/blocto-sdk/src/lib/localStorage/constants.ts
  packages/blocto-sdk/src/lib/localStorage/localStorage.ts
  packages/blocto-sdk/src/lib/localStorage/memoryStorage.ts
  packages/blocto-sdk/src/providers/aptos.ts
  packages/blocto-sdk/src/providers/blocto.ts
  packages/blocto-sdk/src/providers/ethereum.ts
  packages/blocto-sdk/src/providers/solana.ts
  packages/blocto-sdk/src/providers/types/aptos.d.ts
  packages/blocto-sdk/src/providers/types/ethereum.d.ts
  packages/eslint-config-custom/index.js
  packages/eslint-config-custom/package.json
  turbo.json
  yarn.lock
Labels: BugFix

#123 feat: export aptos sign types
  packages/blocto-sdk/src/index.d.ts
Labels: feature

#125 Feature: add jest
  .github/workflows/release-branch.yml
  .github/workflows/test.yml
  adapters/rainbowkit-connector/package.json
  adapters/rainbowkit-connector/src/__tests__/index.test.ts
  package.json
  packages/blocto-sdk/jest.config.js
  packages/blocto-sdk/package.json
  packages/blocto-sdk/src/__tests__/index.test.js
  turbo.json
  yarn.lock
Labels: feature

#128 feat: rainbowkit new version
  .changeset/cool-rings-relate.md
  adapters/rainbowkit-connector/package.json
  adapters/rainbowkit-connector/src/index.ts
  yarn.lock
Labels: feature

#131 docs: update rainbowkit new version
  adapters/rainbowkit-connector/README.md
Labels: feature

#133 Feature: Refactor ethereum provider
  .changeset/pretty-toys-think.md
  packages/blocto-sdk/jest.config.js
  packages/blocto-sdk/package.json
  packages/blocto-sdk/src/__tests__/index.test.js
  packages/blocto-sdk/src/constants.ts
  packages/blocto-sdk/src/lib/getEvmSupport.ts
  packages/blocto-sdk/src/providers/blocto.ts
  packages/blocto-sdk/src/providers/ethereum.ts
  packages/blocto-sdk/src/providers/types/blocto.d.ts
  packages/blocto-sdk/src/providers/types/ethereum.d.ts
  packages/blocto-sdk/src/providers/types/solana.d.ts
  packages/eslint-config-custom/package.json
  yarn.lock
Labels: enhancement, feature

#134 Fix: clean session when disconnect
  .changeset/fluffy-cougars-deny.md
  package.json
  packages/blocto-sdk/src/providers/aptos.ts
  packages/blocto-sdk/src/providers/solana.ts
  yarn.lock
Labels: BugFix
