Repository blocto/blocto-sdk, pull requests merged in 2023-03, with the labels that each got.

#50 [Fix] Pass dapp id to the BE
  src/providers/aptos.ts
  src/providers/ethereum.ts
  src/providers/solana.ts
Labels: BugFix

#49 [Fix] - solana mobile connect
  src/providers/solana.ts
Labels: BugFix

#51 Fix/solana app connect
  package.json
  rollup.config.dev.js
  rollup.config.js
  src/providers/aptos.ts
  src/providers/solana.ts
  src/providers/types/solana.d.ts
  yarn.lock
Labels: BugFix

#52 [Feature] Update server urls to wallet-v2
  src/constants.ts
Labels: feature

#48 [Fix] Reset connected value
  src/providers/aptos.ts
  src/providers/solana.ts
Labels: BugFix

#53 [Refactor] Update auth flow
  src/providers/aptos.ts
  src/providers/ethereum.ts
  src/providers/solana.ts
Labels: Refactor

#56 [Feat] EVM prefill email
  src/lib/is.ts
  src/providers/ethereum.ts
Labels: feature

#58 [Fix] adjust isEmail valid & refactor URLSearchParams use
  src/lib/is.ts
  src/providers/ethereum.ts
Labels: BugFix

#59 [Enhance] Update the URL to request with the prefilled email
  src/providers/ethereum.ts
Labels: feature
