Repository blocto/blocto-sdk, pull requests merged in 2023-06, with the labels that each got.

#135 feat: EIP-1193 batchTx params support web3 sendTx type
  .changeset/short-mails-enjoy.md
  README.md
  adapters/rainbowkit-connector/src/index.ts
  packages/blocto-sdk/src/index.d.ts
  packages/blocto-sdk/src/lib/is.ts
  packages/blocto-sdk/src/lib/localStorage/localStorage.ts
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: enhancement

#142 fix: validation of handleSendTransaction
  .changeset/healthy-lizards-chew.md
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: BugFix

#143 Fix/eth load switchable network promise return
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: BugFix

#144 feat: add sdk ethereum provider test case
  packages/blocto-sdk/src/__tests__/index.test.js
Labels: feature

#145 feat: add sendUserOperation function
  .changeset/dull-pigs-double.md
  packages/blocto-sdk/src/providers/ethereum.ts
  packages/blocto-sdk/src/providers/types/ethereum.d.ts
Labels: feature

#146 Refactor: session key
  .changeset/thin-chairs-tap.md
  packages/blocto-sdk/src/constants.ts
  packages/blocto-sdk/src/lib/localStorage/index.ts
  packages/blocto-sdk/src/lib/responseSessionGuard.ts
  packages/blocto-sdk/src/lib/storage/constants.ts
  packages/blocto-sdk/src/lib/storage/index.ts
  packages/blocto-sdk/src/lib/storage/memoryStorage.ts
  packages/blocto-sdk/src/lib/storage/storage.ts
  packages/blocto-sdk/src/providers/aptos.ts
  packages/blocto-sdk/src/providers/blocto.ts
  packages/blocto-sdk/src/providers/ethereum.ts
  packages/blocto-sdk/src/providers/solana.ts
Labels: Refactor

#150 refactor: exclude rollup-plugin-visualizer in package
  packages/blocto-sdk/package.json
Labels: Refactor

#149 Feature: add blocto wallet contract preset
  .changeset/silly-zoos-fold.md
  packages/blocto-sdk/package.json
  packages/blocto-sdk/rollup.config.js
  packages/blocto-sdk/src/index.d.ts
  packages/blocto-sdk/src/main.ts
  packages/blocto-sdk/src/presets/bloctoAccount.ts
  packages/blocto-sdk/src/providers/types/ethereum.d.ts
  yarn.lock
Labels: feature

#147 feat: add sdk version to authn url params
  .changeset/famous-toes-burn.md
  packages/blocto-sdk/package.json
  packages/blocto-sdk/rollup.config.js
  packages/blocto-sdk/src/providers/aptos.ts
  packages/blocto-sdk/src/providers/ethereum.ts
  packages/blocto-sdk/src/providers/solana.ts
  yarn.lock
Labels: feature

#148 feat: help convert eth_sign and personal_sign string to hex
  .changeset/three-poems-live.md
  packages/blocto-sdk/src/__tests__/index.test.js
  packages/blocto-sdk/src/lib/utf8toHex.ts
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: feature

#151 Refactor: change @metamask/rpc-errors to eth-rpc-errors
  .changeset/perfect-emus-change.md
  packages/blocto-sdk/package.json
  packages/blocto-sdk/src/providers/ethereum.ts
  yarn.lock
Labels: Refactor

#153 feat: support multiple params of wallet_addEthereumChain
  .changeset/sharp-numbers-battle.md
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: feature

#154 Feature/seperate chain status
  .changeset/pre.json
  .changeset/sour-cups-sip.md
  adapters/aptos-wallet-adapter-plugin/CHANGELOG.md
  adapters/aptos-wallet-adapter-plugin/package.json
  adapters/rainbowkit-connector/CHANGELOG.md
  adapters/rainbowkit-connector/package.json
  adapters/wagmi-connector/CHANGELOG.md
  adapters/wagmi-connector/package.json
  adapters/web3-react-connector/CHANGELOG.md
  adapters/web3-react-connector/package.json
  package.json
  packages/blocto-sdk/CHANGELOG.md
  packages/blocto-sdk/package.json
  packages/blocto-sdk/src/__tests__/index.test.js
  packages/blocto-sdk/src/constants.ts
  packages/blocto-sdk/src/index.d.ts
  packages/blocto-sdk/src/lib/responseSessionGuard.ts
  packages/blocto-sdk/src/lib/session.d.ts
  packages/blocto-sdk/src/lib/storage/constants.ts
  packages/blocto-sdk/src/lib/storage/storage.ts
  packages/blocto-sdk/src/main.ts
  packages/blocto-sdk/src/providers/aptos.ts
  packages/blocto-sdk/src/providers/blocto.ts
  packages/blocto-sdk/src/providers/ethereum.ts
  packages/blocto-sdk/src/providers/solana.ts
  packages/blocto-sdk/src/providers/types/aptos.d.ts
  packages/blocto-sdk/src/providers/types/blocto.d.ts
  packages/blocto-sdk/src/providers/types/ethereum.d.ts
  packages/blocto-sdk/src/providers/types/solana.d.ts
Labels: feature

#155 fix: missing type of sendUserOperation
  packages/blocto-sdk/src/providers/types/ethereum.d.ts
Labels: BugFix

#156 fix: api error code
  .changeset/happy-plums-shake.md
  .changeset/pre.json
  packages/blocto-sdk/CHANGELOG.md
  packages/blocto-sdk/package.json
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: BugFix

#157 fix: unstandard errors in ethereum provider
  .changeset/twelve-geckos-jump.md
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: BugFix

#158 fix: add ethereum event listener
  .changeset/hot-turkeys-whisper.md
  packages/blocto-sdk/src/lib/responseSessionGuard.ts
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: BugFix

#161 Fix/catch userop err
  .changeset/good-flowers-fetch.md
  .changeset/great-buttons-invite.md
  .changeset/pre.json
  packages/blocto-sdk/CHANGELOG.md
  packages/blocto-sdk/package.json
  packages/blocto-sdk/src/lib/responseSessionGuard.ts
Labels: BugFix

#163 Fix/update session
  .changeset/eleven-lobsters-buy.md
  packages/blocto-sdk/src/lib/storage/storage.ts
Labels: BugFix

#165 Fix/evm disconnect event
  .changeset/pre.json
  .changeset/rare-dragons-hunt.md
  packages/blocto-sdk/CHANGELOG.md
  packages/blocto-sdk/package.json
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: BugFix
