Repository blocto/blocto-sdk, pull requests merged in 2023-04, with the labels that each got.

#60 [Feature]Add evm chain methods
  src/constants.ts
  src/lib/getEvmSupport.ts
  src/providers/ethereum.ts
  src/providers/types/ethereum.d.ts
  tsconfig.json
Labels: feature

#62 feat: add OP, Arbitrum testnet settings
  src/constants.ts
Labels: feature

#63 Bugfix/aptos login status
  src/providers/aptos.ts
  src/providers/ethereum.ts
  src/providers/solana.ts
Labels: BugFix

#64 Release 0.4.2
  package.json
  src/constants.ts
  src/providers/aptos.ts
  src/providers/ethereum.ts
  src/providers/solana.ts
Labels: release

#68 feat: add changeset settings and init changeset
  .changeset/README.md
  .changeset/config.json
  .changeset/healthy-bobcats-complain.md
  README.md
  package.json
  packages/eslint-config-custom/package.json
  yarn.lock
Labels: feature

#69 docs: add blocto docs link
  README.md
Labels: feature

#70 fix: beta-release script
  .changeset/pre.json
  package.json
Labels: BugFix

#71 feat: add blocto wagmi connector
  .changeset/real-colts-nail.md
  .github/pull_request_template.md
  adapters/aptos-wallet-adapter-plugin/README.md
  adapters/aptos-wallet-adapter-plugin/src/__tests__/index.test.ts
  adapters/aptos-wallet-adapter-plugin/src/index.ts
  adapters/blocto-connector/src/declarations.d.ts
  adapters/blocto-connector/src/index.ts
  adapters/wagmi-connector/.gitignore
  adapters/wagmi-connector/README.md
  adapters/wagmi-connector/package.json
  adapters/wagmi-connector/src/bloctoConnector.ts
  adapters/wagmi-connector/src/bloctoWeb3ModalConfig.ts
  adapters/wagmi-connector/src/index.ts
  adapters/wagmi-connector/tsconfig.json
  adapters/wagmi-connector/vite.config.ts
  adapters/wagmi-connector/yarn.lock
Labels: feature

#75 Feature/change release flow
  .github/workflows/beta-release-pr.yml
  .github/workflows/release-pr.yml
  .gitignore
  package.json
Labels: feature

#76 fix: github release pr action commit msg
  .github/workflows/beta-release-pr.yml
  .github/workflows/release-pr.yml
Labels: BugFix

#74 fix: switchChain handler
  .changeset/swift-beds-rest.md
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: BugFix

#80 fix: signTypeData condition
  .changeset/cool-cars-pretend.md
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: BugFix

#82 fix: use latest in adapters
  .changeset/ninety-waves-whisper.md
  adapters/aptos-wallet-adapter-plugin/package.json
  adapters/blocto-connector/package.json
  adapters/wagmi-connector/package.json
  yarn.lock
Labels: BugFix

#84 feat: add ci create PR from main back to develop
  .github/workflows/pr-labeler.yml
  .github/workflows/release-pr.yml
Labels: feature

#90 feat: add auto publish and fix dev ci
  .github/workflows/beta-release-pr.yml
  .github/workflows/release-pr.yml
  package.json
Labels: feature

#91 docs(adapters): update wagmi-connector README
  adapters/wagmi-connector/README.md
Labels: documentation

#92 docs: add adapter npms to README
  README.md
Labels: documentation, feature
