Repository blocto/blocto-sdk, pull requests merged in 2023-12, with the labels that each got.

#328 Fix/batch transactions send async
  .changeset/polite-wasps-clean.md
  packages/blocto-sdk/src/providers/ethereum.ts
  packages/blocto-sdk/src/providers/types/ethereum.d.ts
Labels: BugFix

#338 feat: v4 batch
  .changeset/afraid-hats-occur.md
  .changeset/eight-pugs-shop.md
  packages/blocto-sdk/src/providers/blocto.ts
  packages/blocto-sdk/src/providers/ethereum.ts
  packages/blocto-sdk/src/providers/types/ethereum.d.ts
Labels: feature

#358 Feat/v4 batch beta ver
  .changeset/pre.json
  adapters/aptos-wallet-adapter-plugin/CHANGELOG.md
  adapters/aptos-wallet-adapter-plugin/package.json
  adapters/connectkit-connector/CHANGELOG.md
  adapters/connectkit-connector/package.json
  adapters/rainbowkit-connector/CHANGELOG.md
  adapters/rainbowkit-connector/package.json
  adapters/wagmi-connector/CHANGELOG.md
  adapters/wagmi-connector/package.json
  adapters/web3-react-connector/CHANGELOG.md
  adapters/web3-react-connector/package.json
  adapters/web3modal-connector/CHANGELOG.md
  adapters/web3modal-connector/package.json
  packages/blocto-sdk/CHANGELOG.md
  packages/blocto-sdk/package.json
  packages/blocto-sdk/src/__tests__/index.test.js
Labels: feature

#359 fix: dappauth test error for eslint
  packages/dappauth/babel.config.cjs
  packages/dappauth/package.json
  packages/dappauth/rollup.config.js
  packages/dappauth/src/ABIs/ERC1271.js
  packages/dappauth/src/index.js
  packages/dappauth/src/utils/index.js
  packages/dappauth/test/test-utils.js
  packages/dappauth/test/unit/contract-mock.js
  packages/dappauth/test/unit/index.test.js
  packages/dappauth/test/unit/jest.config.cjs
  packages/dappauth/test/unit/provider-mock.js
  packages/dappauth/test/unit/test-utils.js
  packages/dappauth/utils.js
  yarn.lock
Labels: BugFix

#360 Feature/l2s
  .changeset/warm-rats-peel.md
  packages/blocto-sdk/src/constants.ts
Labels: feature

#363 feat: dappauth changeset
  .changeset/warm-frogs-drum.md
Labels: enhancement, feature

#362 Fix: wagami connector support chain
  .changeset/four-seals-dance.md
  .changeset/pre.json
  adapters/connectkit-connector/CHANGELOG.md
  adapters/connectkit-connector/package.json
  adapters/rainbowkit-connector/CHANGELOG.md
  adapters/rainbowkit-connector/package.json
  adapters/wagmi-connector/CHANGELOG.md
  adapters/wagmi-connector/package.json
  adapters/wagmi-connector/src/connector.ts
  adapters/web3modal-connector/CHANGELOG.md
  adapters/web3modal-connector/package.json
  packages/blocto-sdk/CHANGELOG.md
  packages/blocto-sdk/package.json
Labels: BugFix

#336 fix: run without cache if test failed
  .github/workflows/test.yml
Labels: BugFix
