Repository blocto/blocto-sdk, pull requests merged in 2024-01, with the labels that each got.

#367 fix: duplicate pop-up authn Iframe
  .changeset/unlucky-masks-heal.md
  adapters/web3-react-connector/src/index.ts
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: bug, BugFix

#372 Fix/existed sdk handle window not defined
  .changeset/long-windows-listen.md
  packages/blocto-sdk/src/providers/aptos.ts
  packages/blocto-sdk/src/providers/ethereum.ts
Labels: bug, BugFix

#377 fix(web3-react): replace eth_accounts with eth_requestAccounts
  .changeset/pink-pumpkins-give.md
  adapters/web3-react-connector/src/index.ts
Labels: BugFix

#379 Feat/add wagmi v2
  .changeset/fair-colts-arrive.md
  .github/workflows/publish.yml
  .github/workflows/release-branch.yml
  .github/workflows/test.yml
  adapters/connectkit-connector/package.json
  adapters/rainbowkit-connector/package.json
  adapters/wagmi-connector/package.json
  adapters/wagmi-connector/src/connector.test.ts
  adapters/wagmi-connector/src/connector.ts
  adapters/wagmi-connector/src/index.ts
  adapters/wagmi-connector/src/util/normalizeChainId.ts
  adapters/web3modal-connector/package.json
  adapters/web3modal-connector/src/index.ts
  yarn.lock
Labels: feature

#389 fix: clear wagmi switch chain error
  .changeset/wicked-shirts-flash.md
  adapters/wagmi-connector/src/connector.ts
Labels: BugFix

#390 Fix/getting wrong chain id in in app browser
  .changeset/afraid-hairs-exercise.md
  adapters/wagmi-connector/src/connector.ts
Labels: BugFix
